name: FMT
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - master
jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x, 10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install terraform

    - name: Run Terraform fmt on push or PR
      run: ./scripts/terraform_fmt.sh