name: Terraform_fmt_check
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install terraform

    - name: Run Terraform fmt on push or PR
      run: ./.github/workflows/scripts/terraform_fmt.sh
    - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: "fmt code"
          add: "*.tf"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}